[font]
size = 11.25

[font.normal]
family = "Hurmit Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hurmit Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CartographCF Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CartographCF Nerd Font"
style = "Bold Italic"
