[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.8
blur = false

[window.padding]
x = 16
y = 8

[cursor.style]
shape = "Beam"
blinking = "On"

[mouse]
hide_when_typing = true
